Repository icgc-argo/dac-api, pull requests merged in 2021-09, with the labels that each got.

#165 v 0.34.0
  package.json
  src/domain/interface.ts
  src/domain/state.ts
  src/routes/applications.ts
Labels: v0.34.0

#188 Rc/0.39.0
  package.json
  src/config.ts
  src/domain/interface.ts
  src/domain/service.ts
  src/domain/state.ts
  src/emails/closed-approved.ts
  src/emails/rejected.ts
  src/test/emails.spec.ts
  src/test/state.spec.ts
Labels: v0.39.0

#191 Rc/0.40.0
  package.json
  src/emails/rejected.ts
Labels: v0.40.0

#194 Rc/0.41.0
  package.json
  src/domain/service.ts
  src/domain/state.ts
  src/test/state.spec.ts
Labels: v0.41.0

#201 rc/0.43.0
  package.json
  src/domain/interface.ts
  src/domain/service.ts
  src/resources/swagger.yaml
  src/test/emails.spec.ts
  src/test/encryption.spec.ts
  src/test/state.spec.ts
  src/utils/misc.ts
Labels: v0.43.0

#207 Rc/0.44.0
  package.json
  src/domain/service.ts
Labels: v0.44.0

#234 🔖 Rc/0.48.0
  package.json
  src/domain/service.ts
  src/emails/closed-approved.ts
  src/resources/swagger.yaml
  src/routes/applications.ts
Labels: v0.48.0
